services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  storage:
    image: redis
    volumes: 
      - ./counter/data:/data
  counter: 
    build: 
      context: ./counter
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - PORT=80
      - REDIS_URL=redis://storage
    command: npm run server
    depends_on:
      - storage
  library:
    build: 
      context: ./library
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./library:/app
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter
    command: npm run server
    depends_on:
      - counter