services:
  storage:
    image: redis
    volumes: 
      - ./counter/data:/data
  counter: 
    image: node:20.10
    working_dir: /app
    volumes:
      - ./counter:/app
    environment:
      - PORT=80
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage
  library:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./library:/app
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter
    command: npm run dev
    depends_on:
      - counter