services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  library:
    image: node:20.10
    restart: always
    working_dir: /app
    volumes:
      - ./library:/app
    ports:
      - 80:3000
    environment:
      - UrlDB=mongodb://root:example@mongo:27017/
      - PORT=3000
      - COUNTER_URL=http://counter
    command: npm run dev
